### Site metadata ###

site_name: Python lang Reference
site_description: 'Python Lang tutorial with examples'
site_url: https://rmechi.github.io

repo_url: https://github.com/rmechi/python
edit_uri: edit/master/docs/docs

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
use_directory_urls: false
extra_css: [style.css]
markdown_extensions:
  - toc:
      permalink: "#"


nav:
  - Home: index.md
  - Tutorial:
      - Arrays: python/arrays.md
      - Slices: python/slices.md
      - GoMaps: python/maps.md

