### Site metadata ###

site_name: aws  Reference
site_description: 'aws tutorial with examples'
site_url: https://rmechi.github.io

repo_url: https://github.com/rmechi/aws
edit_uri: edit/master/docs/docs

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
use_directory_urls: false
extra_css: [style.css]
markdown_extensions:
  - toc:
      permalink: "#"


nav:
  - Home: index.md
  - Tutorial:
      - Arrays: aws/arrays.md
      - Slices: aws/slices.md
      - GoMaps: aws/maps.md

